### ISSUE TITLE
404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by McQueen2063** [pbrissaud/suivi-bourse#299]
**Describe the bug**
Tried default installation via docker compose with default config and get the following stack trace:

> suivi-bourse-app   | time=2023-12-28T16:41:11.297000 level=INFO location=main.py:127:<module> msg="SuiviBourse is running !"
suivi-bourse-app   | time=2023-12-28T16:41:11.773000 level=CRITICAL location=main.py:151:<module> msg="An error occurred"  exception="Traceback (most recent call last):
suivi-bourse-app   |   File \"/home/appuser/main.py\", line 144, in <module>
suivi-bourse-app   |     sb_metrics.run()
suivi-bourse-app   |   File \"/home/appuser/main.py\", line 123, in run
suivi-bourse-app   |     self.expose_metrics()
suivi-bourse-app   |   File \"/home/appuser/main.py\", line 111, in expose_metrics
suivi-bourse-app   |     info_values = label_values + [ticker.info.get('currency', 'undefined'), ticker.info.get('exchange', 'undefined'), ticker.info.get('quoteType', 'undefined')]
suivi-bourse-app   |                                   ^^^^^^^^^^^
suivi-bourse-app   |   File \"/usr/local/lib/python3.11/site-packages/yfinance/ticker.py\", line 138, in info
suivi-bourse-app   |     return self.get_info()
suivi-bourse-app   |            ^^^^^^^^^^^^^^^
suivi-bourse-app   |   File \"/usr/local/lib/python3.11/site-packages/yfinance/base.py\", line 1496, in get_info
suivi-bourse-app   |     data = self._quote.info
suivi-bourse-app   |            ^^^^^^^^^^^^^^^^
suivi-bourse-app   |   File \"/usr/local/lib/python3.11/site-packages/yfinance/scrapers/quote.py\", line 563, in info
suivi-bourse-app   |     self._fetch(self.proxy)
suivi-bourse-app   |   File \"/usr/local/lib/python3.11/site-packages/yfinance/scrapers/quote.py\", line 594, in _fetch
suivi-bourse-app   |     result = self._data.get_raw_json(
suivi-bourse-app   |              ^^^^^^^^^^^^^^^^^^^^^^^^
suivi-bourse-app   |   File \"/usr/local/lib/python3.11/site-packages/yfinance/data.py\", line 75, in get_raw_json
suivi-bourse-app   |     response.raise_for_status()
suivi-bourse-app   |   File \"/usr/local/lib/python3.11/site-packages/requests/models.py\", line 1021, in raise_for_status
suivi-bourse-app   |     raise HTTPError(http_error_msg, response=self)
suivi-bourse-app   | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v6/finance/quoteSummary/AAPL?modules=financialData&modules=quoteType&modules=defaultKeyStatistics&modules=assetProfile&modules=summaryDetail&ssl=true"
suivi-bourse-app exited with code 1

**To Reproduce**
Take files from https://github.com/pbrissaud/suivi-bourse/tree/master/docker-compose (except docker-compose.dev.yaml)
Run docker compose up -d and bam, 404.

**Expected behavior**
I would expect that it gets quotes? :)

**Installation mode:** (choose one)
- [ ] Standalone
- [ ] Docker 
- [x] Docker-Compose

**Environnement:**
Probably not the cause, but: Ubuntu 22.04 Server and Docker version 24.0.7, build afdd53b

PS: I really like your project and would love to use it. But it seems that I stumble over something obvious?! Or did yahoo changed something on their side recently?
I hope it's unlikely that I tried during some yahoo outage.
Also, I probably want to trim down the docker compose file to just the app getting data. I already have prometheus and grafana running... :)

**Comment by McQueen2063** [comment]
could be related to that bug report?
https://github.com/ranaroussi/yfinance/issues/1729
Maybe indeed some yahoo api weirdness? I try to query from Germany, FWIW. I don't have a US VPN or endpoint to test from there, though...

**Comment by pbrissaud** [comment]
H,

Thank you for reaching out and for the detailed information you provided. From my initial observation, it does seem to be an issue related to the Yahoo Finance API.

I'm using the [yfinance](https://github.com/ranaroussi/yfinance) library to fetch financial data from the Yahoo Finance API. In my experience, this API isn't entirely open and tends to change, making it more challenging to query reliably.

I'll investigate if there's an update available for this library and conduct some tests to resolve this. I'll keep you updated on my progress regarding this issue.

Thanks again for bringing this to my attention. I'll be in touch soon with more information.

Best regards,
Paul

**Comment by pbrissaud** [comment]
Hello,

I released a new version (3.6.0) with the latest version of the yfinance library, addressing the issue we discussed earlier. I conducted tests on my end, and they were successful.

All you need to do is modify the Docker image tag to access this updated version.
https://github.com/pbrissaud/suivi-bourse/blob/bd4509cf3bfffbf2a7ddd48c868c2ee181f6d387/docker-compose/docker-compose.yaml

Could you please retest and confirm if everything works smoothly now?

**Comment by McQueen2063** [comment]
Hello,

that was fast! Awesome :)
I gave it a try and get a completely different error now:

> suivi-bourse-app   | time=2023-12-28T19:41:50.884000 level=INFO location=main.py:127:<module> msg="SuiviBourse is running !"
suivi-bourse-app   | time=2023-12-28T19:41:50.910000 level=ERROR location=base.py:1679:_fetch_ticker_tz msg="Failed to get ticker 'AAPL' reason: HTTPSConnectionPool(host='fc.yahoo.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc3d6a4ebd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
suivi-bourse-app   | time=2023-12-28T19:41:50.912000 level=ERROR location=base.py:269:history msg="AAPL: No price data found, symbol may be delisted (period=1mo)"
suivi-bourse-app   | time=2023-12-28T19:41:50.913000 level=CRITICAL location=main.py:151:<module> msg="An error occurred"  exception="Traceback (most recent call last):
suivi-bourse-app   |   File \"/home/appuser/main.py\", line 144, in <module>
suivi-bourse-app   |     sb_metrics.run()
suivi-bourse-app   |   File \"/home/appuser/main.py\", line 123, in run
suivi-bourse-app   |     self.expose_metrics()
suivi-bourse-app   |   File \"/home/appuser/main.py\", line 109, in expose_metrics
suivi-bourse-app   |     last_quote = (history.tail(1)['Close'].iloc[0])
suivi-bourse-app   |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
suivi-bourse-app   |   File \"/usr/local/lib/python3.12/site-packages/pandas/core/indexing.py\", line 1153, in __getitem__
suivi-bourse-app   |     return self._getitem_axis(maybe_callable, axis=axis)
suivi-bourse-app   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
suivi-bourse-app   |   File \"/usr/local/lib/python3.12/site-packages/pandas/core/indexing.py\", line 1714, in _getitem_axis
suivi-bourse-app   |     self._validate_integer(key, axis)
suivi-bourse-app   |   File \"/usr/local/lib/python3.12/site-packages/pandas/core/indexing.py\", line 1647, in _validate_integer
suivi-bourse-app   |     raise IndexError(\"single positional indexer is out-of-bounds\")
suivi-bourse-app   | IndexError: single positional indexer is out-of-bounds"
suivi-bourse-app exited with code 1


Seems like Yahoo is blocking my end now. Maybe I tried too often before... I guess some weird rate limit protection on their end. I'll try again tomorrow, since my residential IP should change every night. (or I'll force a re-dial in later).
Will try again later and report back again!

**Comment by McQueen2063** [comment]
Indeed yahoo is blocking me. What we are seeing is unrelated to your code changes.
Using httpie (http https://fc.yahoo.com), I get the same error:

`http: error: ConnectionError: HTTPSConnectionPool(host='fc.yahoo.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10682c530>: Failed to establish a new connection: [Errno 61] Connection refused')) while doing a GET request to URL: https://fc.yahoo.com/`

**Comment by McQueen2063** [comment]
Well, even after obtaining a new IP, I still get connection refused at fc.yahoo.com. I'll keep on trying the next few days and will report back. But this sure looks like a problem at yahoo's side...

**Comment by pbrissaud** [comment]
Seems weird that Yahoo blocks connections from Germany, no problem in France.

**Comment by pbrissaud** [comment]
Hi, 
Do you think I should consider this issue closed?
